In [1]:
import os
import sys

sys.path.append(os.path.abspath('..'))

In [2]:
from src.chembl_api import search_target
from src.chembl_api import get_bioactivity
from src.chembl_api import get_molecule_properties
from src.chembl_api import get_all_molecule_properties
from src.chembl_api import merge_dataset
from src.chembl_api import build_dataset
target=search_target("EGFR")
print(target)

{'target_chembl_id': 'CHEMBL203', 'organism': 'Homo sapiens', 'pref_name': 'Epidermal growth factor receptor'}

In [ ]:
df = get_bioactivity("CHEMBL203")

In [3]:
df=build_dataset("EGFR",max_molecules=1000)

Searching target...
Target Found : Epidermal growth factor receptor
CHEMBL ID    : CHEMBL203
Downloading bioactivity...
https://www.ebi.ac.uk/chembl/api/data/activity.json?target_chembl_id=CHEMBL203&standard_type=IC50&limit=1000
Next page: /chembl/api/data/activity.json?limit=1000&offset=1000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=1000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=2000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=2000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=3000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=3000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=4000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=4000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=5000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=5000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=6000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=6000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=7000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=7000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=8000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=8000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=9000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=9000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=10000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=10000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=11000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=11000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=12000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=12000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=13000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=13000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=14000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=14000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=15000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=15000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=16000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=16000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=17000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=17000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=18000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=18000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=19000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=19000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=20000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=20000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=21000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=21000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=22000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=22000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=23000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=23000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=24000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=24000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=25000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=25000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: /chembl/api/data/activity.json?limit=1000&offset=26000&target_chembl_id=CHEMBL203&standard_type=IC50
https://www.ebi.ac.uk/chembl/api/data/activity.json?limit=1000&offset=26000&target_chembl_id=CHEMBL203&standard_type=IC50
Next page: None
Bioactivity shape :  (26600, 47)
Bioactivity unique moelcules :  14776
Bioactivity shape : (26600, 47)
Unique molecules : 14776

Downloading molecular properties...
No cache found. Creating new cache.
Cached molecules : 0
Unique molecules : 1000
Molecules to download : 1000
Bioactivity Shape: (26600, 47)
Descriptor Shape: (1000, 5)
Merging datasets...
Done!

C:\Users\Asus\DrugInsightAI\src\chembl_api.py:152: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  cache_df=pd.concat([cache_df,df], ignore_index=True)

In [5]:
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,toid,type,units,uo_units,upper_value,value,logp,hba,hbd,molecular_weight
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.041,4.45,4,3,383.81
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.3,4.45,4,3,383.81
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,7.82,4.45,4,3,383.81
3,None,None,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.17,3.61,6,3,482.90
4,None,None,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.04,3.61,6,3,482.90

In [6]:
df.to_csv("../data/processed/final_dataset.csv", index=False)

In [7]:
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,toid,type,units,uo_units,upper_value,value,logp,hba,hbd,molecular_weight
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.041,4.45,4.0,3.0,383.81
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.3,4.45,4.0,3.0,383.81
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,7.82,4.45,4.0,3.0,383.81
3,None,None,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.17,3.61,6.0,3.0,482.90
4,None,None,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,None,IC50,uM,UO_0000065,None,0.04,3.61,6.0,3.0,482.90

In [8]:
df.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value', 'logp', 'hba', 'hbd',
       'molecular_weight'],
      dtype='object')