In [1]:
import os
import sys
sys.path.append(os.path.abspath('..'))

In [2]:
import pandas as pd
import numpy as np

In [3]:
from src.chembl_api import build_dataset
from src.data_processing import *

In [4]:
df=pd.read_csv("../data/processed/final_dataset.csv")

In [5]:
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,toid,type,units,uo_units,upper_value,value,logp,hba,hbd,molecular_weight
0,NaN,NaN,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,NaN,NaN,BAO_0000190,...,NaN,IC50,uM,UO_0000065,NaN,0.041,4.45,4.0,3.0,383.81
1,NaN,NaN,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,NaN,NaN,BAO_0000190,...,NaN,IC50,uM,UO_0000065,NaN,0.300,4.45,4.0,3.0,383.81
2,NaN,NaN,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,NaN,NaN,BAO_0000190,...,NaN,IC50,uM,UO_0000065,NaN,7.820,4.45,4.0,3.0,383.81
3,NaN,NaN,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,NaN,NaN,BAO_0000190,...,NaN,IC50,uM,UO_0000065,NaN,0.170,3.61,6.0,3.0,482.90
4,NaN,NaN,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,NaN,NaN,BAO_0000190,...,NaN,IC50,uM,UO_0000065,NaN,0.040,3.61,6.0,3.0,482.90

In [6]:
clean_df=clean_dataset(df)

Validating dataset...
Dataset validation passed.
Selecting required columns...
Selecting Columns : 7
Selecting Rows : 2616
Rows before removing missing values: 2616
Rows after removing missing values: 2540
Number of missing value : 76
Rows before removing duplicate values: 2540
Rows after removing duplicate values: 2044
Rows before aggregating standard_values: 2044
Rows after aggregating standard_values: 956
Converting IC50 to pIC50...
Done.
Cleaning completed successfully.

In [8]:
clean_df.head()

,molecule_chembl_id,canonical_smiles,logp,hba,hbd,molecular_weight,pIC50
0,CHEMBL10,C[S+]([O-])c1ccc(-c2nc(-c3ccc(F)cc3)c(-c3ccncc...,4.68,3.0,1.0,377.44,4.334106
1,CHEMBL100714,COc1ccc(Nc2ncnc3cc(OC)c(OC)cc23)cc1OC,3.41,7.0,1.0,341.37,5.552842
2,CHEMBL1009,N[C@@H](Cc1ccc(O)c(O)c1)C(=O)O,0.05,4.0,4.0,197.19,3.345400
3,CHEMBL101581,COc1cc2nccc(Oc3cccc(Br)c3)c2cc1OC,4.81,4.0,0.0,360.21,5.602060
4,CHEMBL104153,COc1ccc(Nc2ncc3cc(-c4c(Cl)cccc4Cl)c(=O)n(C)c3n...,5.05,6.0,1.0,427.29,6.657577

In [10]:
len(clean_df)

956

In [11]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   molecule_chembl_id  956 non-null    object
 1   canonical_smiles    956 non-null    object
 2   logp                956 non-null    float64
 3   hba                 956 non-null    float64
 4   hbd                 956 non-null    float64
 5   molecular_weight    956 non-null    float64
 6   pIC50               956 non-null    float64
dtypes: float64(5), object(2)
memory usage: 52.4+ KB

In [12]:
clean_df.describe()

             logp         hba         hbd  molecular_weight       pIC50
count  956.000000  956.000000  956.000000        956.000000  956.000000
mean     3.854686    5.339958    1.860879        378.773787    5.644143
std      1.460609    1.685949    1.081252        108.290190    1.541102
min     -1.300000    1.000000    0.000000        138.120000    2.187087
25%      2.867500    4.000000    1.000000        296.062500    4.384117
50%      3.870000    5.000000    2.000000        374.830000    5.378022
75%      4.670000    6.000000    2.000000        445.187500    6.806112
max     10.010000   10.000000    8.000000        840.870000   11.220909

In [14]:
clean_df.isnull().sum()

molecule_chembl_id    0
canonical_smiles      0
logp                  0
hba                   0
hbd                   0
molecular_weight      0
pIC50                 0
dtype: int64

In [15]:
clean_df.duplicated().sum()

np.int64(0)

In [16]:
clean_df.head()

,molecule_chembl_id,canonical_smiles,logp,hba,hbd,molecular_weight,pIC50
0,CHEMBL10,C[S+]([O-])c1ccc(-c2nc(-c3ccc(F)cc3)c(-c3ccncc...,4.68,3.0,1.0,377.44,4.334106
1,CHEMBL100714,COc1ccc(Nc2ncnc3cc(OC)c(OC)cc23)cc1OC,3.41,7.0,1.0,341.37,5.552842
2,CHEMBL1009,N[C@@H](Cc1ccc(O)c(O)c1)C(=O)O,0.05,4.0,4.0,197.19,3.345400
3,CHEMBL101581,COc1cc2nccc(Oc3cccc(Br)c3)c2cc1OC,4.81,4.0,0.0,360.21,5.602060
4,CHEMBL104153,COc1ccc(Nc2ncc3cc(-c4c(Cl)cccc4Cl)c(=O)n(C)c3n...,5.05,6.0,1.0,427.29,6.657577